### PR TITLE
Refine Motivation section 

### LINKED ISSUE #402: Make it clearer that it's not necessary to implement a profile to be WoT-compliant
@egekorkan mentioned on the WoT mailing list that "Some within Siemens thought that one must implement a Profile to become a WoT-compliant implementation, which is not the case."

I just re-read the introduction to the WoT Profiles specification and I think section [1.1 Motivation](https://w3c.github.io/wot-profile/#motivation) explains this fairly well, but perhaps there is room for improvement. What text could be added here to make this more clear?

Otherwise, this might be a case of improving documentation elsewhere, such as on the W3C WoT website https://www.w3.org/WoT/documentation/

### PR DESCRIPTION
**Pull request by benfrancis**
Closes #402

***
<a href="https://pr-preview.s3.amazonaws.com/benfrancis/wot-profile/pull/412.html" title="Last updated on May 14, 2024, 2:29 PM UTC (5f32238)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-profile/412/b5cc4e7...benfrancis:5f32238.html" title="Last updated on May 14, 2024, 2:29 PM UTC (5f32238)">Diff</a>

### CODE REVIEW

**Review by lu-zero — APPROVED** [review]
It sounds good to me.

Thank you!

**Comment by lu-zero** [comment]
As per today's meeting, @mmccool could you please give it a read and if it convinces you as well, I'd land it asynchronously.

**Comment by benfrancis** [comment]
Following today's Profiles task force meeting, @chachamimm I would be grateful if you could review this.

As a non-normative change it just requires one existing editor to review it in order for it to land.

Thank you

**Comment by lu-zero** [comment]
As per today call, the patch can land.

 @mmccool, since you seem busy we land this patch during the call instead of asynchronously.

**Pull request merged**
