### PR TITLE
Issue 45 - FPWD clarifications on profile name and figures

### PR DESCRIPTION
**Pull request by mlagally**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/47.html" title="Last updated on Oct 7, 2020, 11:23 AM UTC (d5e6f7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-profile/47/2b8cf9f...d5e6f7f.html" title="Last updated on Oct 7, 2020, 11:23 AM UTC (d5e6f7f)">Diff</a>

### CODE REVIEW

**Comment by mmccool** [comment]
So yet again, I want to say that I agree with the "core" name if it is in fact defined to be the set of constraints common to all profiles (eg http-specific profiles, etc).

**Comment by mmccool** [comment]
So I had some further thoughts on this:
1. I would like to confirm whether Sebastian has the "target specific verticals" use case in mind for profiles.  I think this is a different use case than "out of the box interoperability".  We need to resolve whether or not we want to extend the scope of the profile spec to support profiles for "verticals" as well (which may indeed have other constraints than what we currently have in the "core").
2. Assuming we resolve to the scope extension in 1, then I would propose we have two "categories" of profiles: "core" and "non-core" (or maybe "vertical").  The former's primary goal is interoperability.  If you as a user want that, then you select it.  If you need to work with pre-existing brownfield systems in particular verticals, however, you might have to select a non-core profile aimed at those verticals.
3. We could rename "core" to "interop".

**Comment by egekorkan** [comment]
Why not _simply_ name the current core profile to _simple_ profile? This is a profile that is easy to implement, uses very conventional mechanisms and protocols, and would achieve interoperability by being easy, not necessarily because many people have already implemented Things that respect this. If this profile is created because it was identified that the Thing implementations by the WG respect this profile _already_, this claim should be proven. We have all the data to show whether this is the case or not.

I also strongly object naming any profile core since, in an environment like Web that is constantly changing, no set of technologies can be core for more than 5 (10?) years. I have also mentioned somewhere that we can name profiles by more atomic features, like `"profile":["http","json","sse","simpleDataSchema", "humanMetaData"]`. Then, we can say that if all these atomic profiles are respected, it can be called _myProfile_. I also don't like _interop_ since it would give the impression that other profiles do not provide interoperability.

**Comment by danielpeintner** [comment]
Note: there is a dedicated issue w.r.t. the name, see https://github.com/w3c/wot-profile/issues/21
I suggest having discussions there ;-)

**Comment by mlagally** [comment]
We are mixing two topics in this conversation, the profile **name** and the profile **scope and use cases**.
Let's treat them separately to make sure we address the individual qustions.

We already did a resolution on the **scope** of the profile in several arch calls back in July:

> RESOLUTION: Accepting the following requirements for the FPWD: Interoperability, Limit and reduce complexity, Eliminate ambiguities, Limit resource consumption, finite set of features and capabilities, follow security and privacy best practices subject to group feedback.

The current FPWD draft addresses this scope.

**Out of the box interoperability** is the main objective of the core profile. The conformance section provides the corresponding guarantees. 

@egekorkan Please consider that deployed WoT devices are different to Web devices, i.e. in many cases they don't undergo regular SW maintenance and updates. There's no business model for providing updates, which is the reason why the security problems we see in many IoT devices (e.g. IP cameras) don't get fixed.
Nothing is set in stone in the Web and in WoT forever. If we define a Core 1.0 which will hold for 5 years we whould have done an excellent job. There's always room for defining other profiles or a new version of the FPWD profile, if there are new requirements.

**Comment by sebastiankb** [comment]
@mlagally 
>We are mixing two topics in this conversation, the profile name and the profile scope and use cases.
Let's treat them separately to make sure we address the individual qustions.

+1

I think, for the name issue we already clarified this yesterday and the corresponding editorial note is included. Regarding the name I already shared my view in July on this:

https://github.com/w3c/wot-profile/issues/21

>RESOLUTION: Accepting the following requirements for the FPWD: Interoperability, Limit and reduce complexity, Eliminate ambiguities, Limit resource consumption, finite set of features and capabilities, follow security and privacy best practices subject to group feedback.

This very generic RESOLUTION is fine and does not directly touch my concern. 

In general, different people have a different understanding what is understood  by "interoperability". Especially, in IoT with its different domains there is not an easy answer to that. I already shared my view on this here:

https://github.com/w3c/wot-profile/issues/25#issuecomment-669878424

As you can see, I'm agree that we have a support for an OotBI Profile such as for Thing2Browser and Thing2Cloud scenarios. 

However, we should make clear in the FPWD, that this is a kind of "offer" for developer that can be followed to possible the interoperability in your  there may other Profiles that  

what is missing that "core" is one profile of man  it should clear in specification that it should be not the core for all kind of WoT scenarios. 
I just to want make clear in the current document that the "core" is not a mandatory thing which have to be NOT implemented when you prefer a different profile, which is, e.g., more relevant for healthcare scenarios and

**Comment by sebastiankb** [comment]
@mlagally 
>We are mixing two topics in this conversation, the profile name and the profile scope and use cases.
Let's treat them separately to make sure we address the individual qustions.

+1

I think, for the name issue we already clarified this yesterday and the corresponding editorial note is included. Regarding the name I already shared my view in July on this:

https://github.com/w3c/wot-profile/issues/21

>RESOLUTION: Accepting the following requirements for the FPWD: Interoperability, Limit and reduce complexity, Eliminate ambiguities, Limit resource consumption, finite set of features and capabilities, follow security and privacy best practices subject to group feedback.

This very generic RESOLUTION is fine, but does not touch my concern directly.

In general, different people have a different understanding what is understood  by "interoperability". Especially, in IoT with its different domains there is not an easy answer to that. I already shared my view on this here:

https://github.com/w3c/wot-profile/issues/25#issuecomment-669878424

As you can see, I'm agree that we have a support for an OotBI Profile such as for Thing2Browser and Thing2Cloud scenarios. I think all thing vendors who want to launch such new devices with this purpose in mind will be glad to know that there is some sort of profile that can be followed to enhance the OotBI. However, we also have other scenarios such as Thing2Thing or Thing2Edge where the “core” profile does not make sense since there are different data model and protocol constraints. I just want to point out that “core” is only one of many profiles and consumer shall NOT be forced to implement always the “core” when it does not make sense in there context / domain.

**Comment by sebastiankb** [comment]
@mlagally
> Is there a description of the four scenarios you refer to and their requirements?

Actually, there are more:

https://www.w3.org/TR/wot-architecture/#sec-architecture-overview 

Expected requirements (e.g. for protocols usage):

https://www.w3.org/TR/wot-architecture/#sec-binding-templates
 
>I'm not sure I agree to your view that a constrained profile does not make sense for Thing2Thing and Thing2Edge scenarios.

I did not write that! 
And again, I support the profile concept. However, I do not support a "core" profile that have to be always part of other (future) profiles.

**Pull request merged**
